import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { AppContextProvider } from "./context/contextApi";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <AppContextProvider>
          <Header />
          {children}
        </AppContextProvider>
      </body>
    </html>
  );
}
